#!/bin/sh

makexml()
{
    filecxx=${1}.cxx 
    fileh=${1}.h 
    filecxxxml=check/${filecxx}.xml
    filehxml=check/${fileh}.xml

    dirv=`dirname ${filehxml}` 
    do=n

    [ -d ${dirv} ] || mkdir -p ${dirv} 

    if [ -r ${filecxx} ] ; then
	if [ ${filecxx} -nt ${filecxxxml} ] ; then
	    src2srcml ${filecxx} ${filecxxxml} 
	    do=y
	fi
#    else
#	cp -p $irst/dummy.cxx.xml ${filecxxxml} 
    fi
	
    if [ -r ${fileh} ] ; then
	if [ ${fileh} -nt ${filehxml} ] ; then
	    src2srcml ${fileh} ${filehxml} 
	    do=y
	fi
#    else
#	iprot=`basename ${1} | tr [:lower:] [:upper:]`
#	cat $irst/dummy.h.xml | sed -e "s/DUMMY/${iprot}/" > ${filehxml}
#	touch -r $irst/dummy.h.xml ${filehxml} 
    fi
    
    if [ "$do" == "y" ] ; then 
#	echo ${filecxxxml} ${filehxml}
	touch $ALICE_ROOT/reFact
    fi
}

makeviol()
{
    viols=check/${1}.viol
    filecxxxml=check/${1}.cxx.xml
    filehxml=check/${1}.h.xml

    if [ ${filehxml}   -nt ${viols} ] || [ ${filecxxxml} -nt ${viols} ] ; then
	echo ${viols}
	java -Xmx500m -jar $irst/NewRuleChecker/NewRuleChecker.jar ${filecxxxml} ${filehxml} \
	${ALICE_ROOT}/factFile.xml $irst/NewRuleChecker/config/AliceCodingConventions.xml > ${viols}
    fi
}

srcdirs()
{
    find . -mindepth 1 -maxdepth 1 -type d |\
                               grep -v bin |\
                               grep -v doc |\
                               grep -v etc |\
                               grep -v lib |\
                               grep -v man |\
                              grep -v data |\
                              grep -v html |\
                              grep -v test |\
                             grep -v build |\
                             grep -v cmake |\
                             grep -v picts |\
                             grep -v share |\
                            grep -v macros |\
                           grep -v include |\
                          grep -v roothxml 
}
    
getstubs()
{
    find . -name '*.cxx' -or -name '*.h' |\
                      sed -e 's/\.cxx//' |\
                        sed -e 's/\.h//' |\
                       sed -e 's?^\./??' |\
                             grep -v G__ |\
                         grep -v LinkDef |\
                              grep -v \# |\
                                 sort -u
}



irst=$HOME/Alice/ALICENewRuleChecker
cd $ALICE_ROOT
changed=n


echo ========================================= Creating xml files =========================================
#for i in `srcdirs` ;\
for i in ./MUON ;\
   do cd $i \;
      for j in `getstubs` ; \
         do makexml $j ;\
            done ;\
      cd $ALICE_ROOT ;\
done

echo ================================== Creating files for root includes ==================================
cd $ALICE_ROOT
[ -d roothxml ] || mkdir roothxml
cd roothxml
ln -s $ROOTSYS/include/* . 2>/dev/null
for i in `ls *.h | grep -v G__` ; do makexml `echo $i | sed -e 's/\.h//'` ; done
cd $ALICE_ROOT

if [ reFact -nt factFile.xml ] ; then 
    echo ======================================== Rebuilding fact file ========================================
    java -Xmx500m -jar $irst/FactExtractor/FactExtractor.jar ./ ./
fi

echo ========================================= Creating viol files ========================================
#for i in `srcdirs` ;\
for i in ./MUON ;\
   do cd $i \;
      for j in `getstubs` ; \
      do makeviol $j ;\
         done ;\
      cd $ALICE_ROOT ;\
done




