#cloud-config

package_update: true

apt:
  sources:
    alisw-ppa:
      source: ppa:alisw/ppa

packages:
  - autoconf
  - automake
  - autopoint
  - bison
  - build-essential
  - cmake
  - curl
  - environment-modules
  - flex
  - gcc-10
  - gettext
  - gfortran-10
  - git
  - libbz2-dev
  - libcurl4-gnutls-dev
  - libfftw3-dev
  - libglfw3-dev
  - libglu1-mesa-dev
  - liblzma-dev
  - libmysqlclient-dev
  - libnanomsg-dev
  - libncurses-dev
  - libperl-dev
  - libtbb-dev
  - libtool
  - libtool-bin
  - libxml2-dev
  - lsb-release
  - ncdu
  - ninja-build
  - pkg-config
  - python-is-python3
  - python3-alibuild
  - python3-dev
  - python3-pip
  - python3-venv
  - ripgrep
  - rsync
  - software-properties-common
  - swig
  - texinfo
  - tree
  - unzip
  - xorg-dev


runcmd:
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
    - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
    - update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 10
    - git clone "https://github.com/AliceO2Group/AliceO2.git" /home/ubuntu/alice/O2
    - chown -R ubuntu.ubuntu /home/ubuntu/

final_message: "The system is finally up, after $UPTIME seconds"

