#!/bin/sh

darchive2volume() {
	# reverse operation from dvolume2archive : take an archive and populate
	# a volume with it
	# will fail if the target volume already exist !

	local volume_name=$2

	local archive_dir=$(cd $(dirname $1) && pwd)
	local archive=$(basename $1)

    echo "volume_name=$volume_name"
	echo "archive_dir=$archive_dir archive=$archive"
	
	$(docker volume ls | grep $volume_name >/dev/null 2>&1)

	if [ $? = 0 ]; then
		printf "%s\\n" "volume $volume_name already exists ! will not overwrite it !"
	else
		docker run -it --rm -v $volume_name:/dest -v $archive_dir:/src alpine:3.5 tar -zxvf /src/$archive -C /dest
	fi
}

darchive2volume $1 $2
